Update update-weather.yml

diff --git a/.github/workflows/update-weather.yml b/.github/workflows/update-weather.yml
--- a/.github/workflows/update-weather.yml
+++ b/.github/workflows/update-weather.yml
@@ -71,7 +71,13 @@ jobs:
           git clone https://github.com/SergKorol/PostDevToLi.git
           cd PostDevToLi/PostDevToLi
           dotnet build
-          cp ../../data/posted_articles.db ./bin/Debug/net8.0/
+          if [ -f ../../data/posted_articles_new.db ]; then
+              cp ../../data/posted_articles.db ./bin/Debug/net8.0/
+              if [ $? -ne 0 ]; then
+              echo "Error: Failed to copy the database."
+              exit 1
+              fi
+          fi
           ls -R
           dotnet restore
           dotnet run --project PostDevToLi.csproj -- \
